image: Visual Studio 2017
platform: x64

environment:
  PLAIDML_DEVICE_IDS: opencl_cpu.0
  PLAIDML_EXPERIMENTAL: 1
  PLAIDML_TELEMETRY: 0

  matrix:  
    # - CONDA_PREFIX: C:\Miniconda36-x64
    #   PY2: 0
    - CONDA_PREFIX: C:\Miniconda-x64
      PY2: 1

install:
  - cmd: if %PY2% == 1 appveyor DownloadFile https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi
  - cmd: if %PY2% == 1 msiexec /i VCForPython27.msi /qn /quiet /norestart
  - cmd: if not exist opencl_runtime_16.1.2_x64_setup.msi appveyor DownloadFile http://registrationcenter-download.intel.com/akdlm/irc_nas/12512/opencl_runtime_16.1.2_x64_setup.msi
  - cmd: msiexec /i opencl_runtime_16.1.2_x64_setup.msi /qn /quiet /norestart
  - cmd: PATH=%CONDA_PREFIX%;%CONDA_PREFIX%\Scripts;%CONDA_PREFIX%\Library\bin;%PATH%
  - cmd: conda install -y -c conda-forge protobuf numpy
  - cmd: pip install pytest-runner "setuptools>=39"

build_script:
  - cmd: python setup.py test

cache:
  - opencl_runtime_16.1.2_x64_setup.msi
